config/routes.rb
Rails.application.routes.draw do
  resources :schools
  resources :courses
  resources :users
  resources :course_users

  root 'static_pages#home'

  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get 'schools/:id/courses', to: 'courses#index'
  get 'schools/:id/courses/new', to: 'courses#new'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post 'schools/:id/courses/create', to: 'courses#create'

  match '/404', :to => 'errors#not_found', :via => :all
  match '/500', :to => 'errors#internal_server_error', :via => :all
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>
  Do you expect me to talk? No, Mr. Bond, I expect you to About.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Colour me your colour, baby.
</p>
<p>
  Colour me your car.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  This is presumably where you will get help.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to DaveNotes</h1>
  <h2>This is probably home.</h2>
  <p><%= link_to 'Schools', schools_path, class: 'btn btn-lg btn-primary'  %></p>
  <% if logged_in? %>
    <p>Link to your favourite schools</p>
    <p>Link to your favourite courses</p>
  <% else %>
    <%= link_to 'Sign up', signup_path, class: 'btn btn-lg btn-primary' %>
  <% end %>
</div>