config/routes.rb
Rails.application.routes.draw do
  resources :schools
  resources :courses
  resources :users
  resources :course_users

  root 'static_pages#home'

  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get 'schools/:id/courses', to: 'courses#index'
  get 'schools/:id/courses/new', to: 'courses#new'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post 'schools/:id/courses/create', to: 'courses#create'

  match '/404', :to => 'errors#not_found', :via => :all
  match '/500', :to => 'errors#internal_server_error', :via => :all
end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :courses, dependent: :destroy

  validates :name,  presence: true, length: { maximum: 255 }
  validates :country, presence: true, length: { maximum: 255 }
  validates :website, presence: true, length: { maximum: 255 }
  validates :primary_colour, presence: true, length: { maximum: 31 }
  validates :secondary_colour, presence: true, length: { maximum: 31 }
  validates :text_colour, presence: true, length: { maximum: 31 }

  def self.search(search)
    where("lower(name) LIKE lower(?) OR lower(country) LIKE lower(?)", "%#{search}%", "%#{search}%")
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :admin_user, only: [:destroy, :edit, :update]

  def index
    if params[:search]
      schools = School.search(params[:search])
    else
      schools = School.all
    end
    @schools = schools.where(:active => true).paginate(:page => params[:page], :per_page => 5).order('name ASC, country ASC')
  end

  def show
    @school = School.find(params[:id])
    if params[:search]
      courses = @school.courses.search(params[:search])
    else
      courses = @school.courses.all
    end
    @courses = courses.paginate(:page => params[:page], :per_page => 5).order('code ASC, title ASC')
  end

  def new
    @school = School.new
  end

  def edit
    @school = School.find(params[:id])
  end

  def update
    @school = School.find(params[:id])

    if @school.update(school_params)
      if params[:commit] == "Preview"
        render 'edit'
      else
        @school.update(:active => true)
        redirect_to @school
      end
    else
      render 'edit'
    end
  end

  def create
    @school = School.new(school_params)

    if @school.save
      redirect_to @school
    else
      render 'new'
    end
  end

  def destroy
    @school = School.find(params[:id])
    @school.destroy

    redirect_to schools_path
  end

  private

  def school_params
    params.require(:school).permit(:name, :country, :website, :primary_colour,
                                   :secondary_colour, :text_colour)
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_school.html.erb
<%= link_to school, {:style=>"color:#{school.text_colour};text-decoration:none"} do %>
  <li style="color:<%= school.text_colour%>;
      background-color:<%= school.primary_colour %>; border-color:<%= school.secondary_colour %>">
    <span class="glyphicon glyphicon-education" style="color:<%= school.secondary_colour %>" aria-hidden="true"></span>
    <%= school.name %>,
    <%= school.country %>
    <% if current_user && current_user.admin? %>
        | <%= link_to 'delete', school, method: :delete,
                      data: { confirm: 'You sure?' } %>
    <% end %>
    <span class="glyphicon glyphicon-education" style="color:<%= school.secondary_colour %>" aria-hidden="true"></span>
  </li>
<% end %>

app/views/schools/edit.html.erb
<% provide(:title, @school.name) %>
<%= form_for :school, url: school_path(@school), method: :patch do |f| %>

    <% if @school.errors.any? %>
        <div id='error_explanation'>
          <h2>
            <%= pluralize(@school.errors.count, 'error') %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @school.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :country %><br>
      <%= f.text_field :country %>
    </p>

    <p>
      <%= f.label :website %><br>
      <%= f.text_field :website %>
    </p>

    <p>
      <%= f.label :primary_colour %><br>
      <%= f.text_field :primary_colour %>
    </p>

    <p>
      <%= f.label :secondary_colour %><br>
      <%= f.text_field :secondary_colour %>
    </p>

    <p>
      <%= f.label :text_colour %><br>
      <%= f.text_field :text_colour %>
    </p>

    <p>
      <%= f.submit 'Preview' %>
      <%= f.submit %>
    </p>

<% end %>

<ul class="schools">
  <%= render @school %>
</ul>

<%= link_to 'Destroy', school_path(@school),
            method: :delete,
            data: { confirm: 'Are you sure?' } %>

app/views/schools/index.html.erb
<% provide(:title, 'Schools') %>
<h1>List of schools</h1>

<%= link_to 'Add school', new_school_path %>


    <%= form_tag(schools_path, :method => 'get') do %>
      <%= text_field_tag :search, params[:search], placeholder: 'Search Schools', class: 'form-control' %>

      <%= submit_tag 'search', :name => nil, class: 'btn btn-primary' %>
    <% end %>


<%= will_paginate @schools %>

<ul class="schools">
  <%= render @schools %>
</ul>

<%= will_paginate @schools %>

app/views/schools/new.html.erb
<% provide(:title, 'New School') %>
<h1>New School</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@school) do |f| %>

      <%= f.label :name %><br>
      <%= f.text_field :name, class: 'form-control'  %>

      <%= f.label :country %><br>
      <%= f.text_field :country, class: 'form-control'  %>

      <%= f.label :website %><br>
      <%= f.text_field :website, class: 'form-control'  %>

      <%= f.submit 'Create School', class: 'btn btn-primary' %>
    <% end %>

    <%= link_to 'Back to Schools', schools_path %>
  </div>
</div>

app/views/schools/show.html.erb
<% provide(:title, @school.name) %>
<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @school.country %>
</p>

<p>
  <strong>Website:</strong>
  <%= @school.website %>
</p>

<% if !@school.active %>
  <p>This school is being reviewed to make sure it's a real school.</p>
<% else %>
  <% if current_user %>
    <p><%= link_to 'add course', "#{@school.id.to_s}/courses/new" %></p>
  <% end %>
<% end %>

<p><%= link_to 'back', schools_path %></p>

<% if current_user && current_user.admin? %>
  <p><%= link_to 'edit', edit_school_path(@school) %></p>
<% end %>

<%= form_tag("/schools/ #{@school.id.to_s}", :method => 'get') do %>
    <%= text_field_tag :search, params[:search], placeholder: 'Search Courses' %>
    <%= submit_tag 'search', :name => nil %>
<% end %>

<% if @courses.size > 0 %>
  <table>
    <thead>
      <tr>
        <th>Code</th>
        <th>Title</th>
      </tr>
    </thead>

    <% @courses.each do |course| %>
      <tr>
        <td>
          <%= link_to course.code, course,
                    {:style=>'color:black; text-decoration:none'} %>
        </td>
        <td><%= course.title %></td>
      </tr>
    <% end %>
  </table>
<% end %>

<%= will_paginate @courses %>